### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by gagarski** [antropovaa/Uniq#2]
1. Создалось впечатление, что для тестов вы одновременно используете две версии JUnit. Аннотация `org.junit.Test` из четвёртой версии, а `org.junit.jupiter.api.Assertions` - из пятой. Приведите всё к одной версии. (В пятой версии JUnit аннотация Test в другом пакете)
2. "Создалось впечатление" из предыдущего пункта - это плохо, поскольку угадывать, от каких библиотек зависит ваш проект мне пришлось самостоятельно. Есть два варианта решить эту проблему. Сложнее, добавить файл для сборки через Maven или Gradle (плюс в том, что можно собирать проект в другой среде разработки или без неё вообще). Проще, добавить в репозиторий файл `Uniq.iml` (в вашем проекте он единственный источник информации о зависимостях).
3. Уберите конкретные типы (например, `ArrayList`) и замените их на интерфейсы, где это возможно.
4. Для ввода текста в увас получился общий код, а для вывода получилось одно большое ветвление. Вывод можно также организовать с помощью общего кода.

**Comment by antropovaa** [comment]
Исправила. Насчет 4 пункта, если я правильно поняла, то ветвление должно было быть только в случае проверки того, куда именно выводить строчки, а сам вывод должен производиться независимо? Если так, то исправила это.
